// frontend/src/pages/connect-scenario-library-editor/library-editor.dsl.ts
import { DSL_QUOTED_TOKEN_PATTERN, formatDslLiteral, readQuotedToken } from '../../components/dsl/dsl.quotes';
import type { DefData } from '../../modules/connect-scenario/helpers/def-editor.render';

const GOAL_VARIABLE_TOKEN_PATTERN = String.raw`(?:\[[^\]\r\n]*\]|${DSL_QUOTED_TOKEN_PATTERN})`;
const GOAL_SET_LINE_RX = new RegExp(`^(\\s*)SET\\s+(${GOAL_VARIABLE_TOKEN_PATTERN})\\s*(?:=\\s*)?(${GOAL_VARIABLE_TOKEN_PATTERN})\\s*$`);
const GOAL_OPT_LINE_RX = new RegExp(`^(\\s*)OPT\\s+(${GOAL_VARIABLE_TOKEN_PATTERN})\\s+(${GOAL_VARIABLE_TOKEN_PATTERN})\\s*$`);

export interface GoalVariableLineMatch {
  indent: string;
  type: 'set' | 'opt';
  varName: string;
  value: string;
}

function parseGoalVariableToken(token: string): string {
  const raw = String(token ?? '').trim();
  if (raw.startsWith('[') && raw.endsWith(']')) {
    return raw.slice(1, -1).trim();
  }
  return readQuotedToken(raw).value.trim();
}

export function parseGoalVariableLine(line: string): GoalVariableLineMatch | null {
  const raw = String(line ?? '');

  const setMatch = GOAL_SET_LINE_RX.exec(raw);
  if (setMatch) {
    return {
      indent: setMatch[1],
      type: 'set',
      varName: parseGoalVariableToken(setMatch[2]),
      value: parseGoalVariableToken(setMatch[3])
    };
  }

  const optMatch = GOAL_OPT_LINE_RX.exec(raw);
  if (optMatch) {
    return {
      indent: optMatch[1],
      type: 'opt',
      varName: parseGoalVariableToken(optMatch[2]),
      value: parseGoalVariableToken(optMatch[3])
    };
  }

  return null;
}

export function formatGoalVariableLine(type: 'set' | 'opt', varName: string, value: string, indent = ''): string {
  return `${indent}${type.toUpperCase()} ${formatDslLiteral(varName)} ${formatDslLiteral(value)}`;
}

export function replaceGoalVariableLineValue(line: string, varName: string, newValue: string): string {
  const parsed = parseGoalVariableLine(line);
  if (!parsed || parsed.varName !== varName) {
    return line;
  }
  return formatGoalVariableLine(parsed.type, parsed.varName, newValue, parsed.indent);
}

/** Generate DSL code from goals */
export function generateDslFromGoals(defData: DefData): string {
  const goals = defData.library.goals || [];
  
  if (goals.length === 0) {
    return '// Brak zdefiniowanych czynności GOAL';
  }
  
  const dslLines: string[] = [];
  
  goals.forEach((goal, index) => {
    dslLines.push(`GOAL ${goal.name}`);
    
    if (goal.code && goal.code.trim()) {
      // Process the goal code to fix DSL syntax
      const processedCode = processDslCode(goal.code.trim());
      dslLines.push(processedCode);
    }
    
    // Add separator between goals (except after last one)
    if (index < goals.length - 1) {
      dslLines.push('');
      dslLines.push('');
    }
  });
  
  return dslLines.join('\n');
}

/** Process DSL code to fix indentation and IF/END blocks */
export function processDslCode(code: string): string {
  const lines = code.split('\n');
  const processedLines: string[] = [];
  let ifDepth = 0;
  
  for (let i = 0; i < lines.length; i++) {
    let line = lines[i].trim();
    
    // Skip empty lines
    if (!line) continue;
    
    // Remove existing indentation
    line = line.replace(/^[\s\t]+/, '');
    
    // Handle IF statements
    if (line.startsWith('IF ')) {
      processedLines.push(line);
      ifDepth++;
    }
    // Handle ELSE statements
    else if (line.startsWith('ELSE')) {
      processedLines.push(line);
    }
    // Handle END statements
    else if (line === 'END' || line.startsWith('END ')) {
      if (ifDepth > 0) {
        processedLines.push('END');
        ifDepth--;
      }
    }
    // Handle other statements (TASK, SET, OUT, etc.)
    else {
      // Add proper indentation for content inside IF blocks
      if (ifDepth > 0) {
        processedLines.push(`  ${line}`);
      } else {
        processedLines.push(line);
      }
    }
  }
  
  // Close any unclosed IF blocks
  while (ifDepth > 0) {
    processedLines.push('END');
    ifDepth--;
  }
  
  return processedLines.join('\n');
}

/** Generate DEF code (JavaScript format) */
export function generateDefCode(defData: DefData): string {
  const { systemVars, optDefaults, library } = defData;
  
  const code = `// DSL Definition - Generated by DEF Editor
// ${new Date().toISOString()}

const systemVars = ${JSON.stringify(systemVars, null, 2)};

const optDefaults = ${JSON.stringify(optDefaults || {}, null, 2)};

const library = ${JSON.stringify({
    objects: library.objects,
    functions: library.functions,
    params: library.params,
    units: library.units,
    logs: library.logs || [],
    alarms: library.alarms || [],
    errors: library.errors || [],
    funcs: library.funcs || []
  }, null, 2)};

const objectFunctionMap = ${JSON.stringify(library.objectFunctionMap || {}, null, 2)};

const paramUnitMap = ${JSON.stringify(library.paramUnitMap || {}, null, 2)};

// Get functions for object
const getFunctionsForObject = (objectName) => {
  return objectFunctionMap[objectName]?.functions || library.functions;
};

// Get units for parameter
const getUnitsForParam = (paramName) => {
  return paramUnitMap[paramName]?.units || library.units;
};

// Get parameter value
const getParamValue = (paramName) => systemVars[paramName] ?? null;

// Set parameter value
const setParamValue = (paramName, value) => { systemVars[paramName] = value; };

// Export
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { systemVars, library, objectFunctionMap, paramUnitMap, getFunctionsForObject, getUnitsForParam, getParamValue, setParamValue };
} else if (typeof exports !== 'undefined') {
  Object.assign(exports, { systemVars, library, objectFunctionMap, paramUnitMap, getFunctionsForObject, getUnitsForParam, getParamValue, setParamValue });
}
`;
  return code;
}

/** Generate library JSON for database storage */
export function generateLibraryJson(defData: DefData): string {
  const { library } = defData;
  const json: Record<string, unknown> = {
    objects: library.objects || [],
    functions: library.functions || [],
    params: library.params || [],
    units: library.units || [],
    actions: library.actions || [],
    logs: library.logs || [],
    alarms: library.alarms || [],
    errors: library.errors || [],
    funcs: library.funcs || [],
    goals: library.goals || []
  };
  
  // Include varRoles if any are defined
  const varRoles = (library as any).varRoles;
  if (varRoles && Object.keys(varRoles).length > 0) {
    json.varRoles = varRoles;
  }
  
  return JSON.stringify(json);
}

/** Generate config JSON for database storage */
export function generateConfigJson(defData: DefData): string {
  const { systemVars, optDefaults, library } = defData;
  return JSON.stringify({
    systemVars: systemVars || {},
    optDefaults: optDefaults || {},
    objectFunctionMap: library.objectFunctionMap || {},
    paramUnitMap: library.paramUnitMap || {}
  });
}

/** Generate pretty-printed library JSON for source editor */
export function generateLibraryJsonPretty(defData: DefData): string {
  const { library } = defData;
  const json: Record<string, unknown> = {
    objects: library.objects || [],
    functions: library.functions || [],
    params: library.params || [],
    units: library.units || [],
    logs: library.logs || [],
    alarms: library.alarms || [],
    errors: library.errors || [],
    funcs: library.funcs || [],
    goals: library.goals || []
  };
  
  // Include varRoles if any are defined
  const varRoles = (library as any).varRoles;
  if (varRoles && Object.keys(varRoles).length > 0) {
    json.varRoles = varRoles;
  }
  
  return JSON.stringify(json, null, 2);
}

/** Extract SET/OPT variables from all GOALs for display */
export function extractSetVarsFromGoals(defData: DefData): Array<{ goalName: string; goalIdx: number; varName: string; value: string; type: 'set' | 'opt'; lineIdx: number }> {
  const goals = defData.library.goals || [];
  const vars: Array<{ goalName: string; goalIdx: number; varName: string; value: string; type: 'set' | 'opt'; lineIdx: number }> = [];
  
  for (let goalIdx = 0; goalIdx < goals.length; goalIdx++) {
    const goal = goals[goalIdx];
    const code = goal.code || '';
    const lines = code.split('\n');
    
    for (let lineIdx = 0; lineIdx < lines.length; lineIdx++) {
      const parsed = parseGoalVariableLine(lines[lineIdx]);
      if (parsed) {
        vars.push({
          goalName: goal.name,
          goalIdx,
          varName: parsed.varName,
          value: parsed.value,
          type: parsed.type,
          lineIdx
        });
      }
    }
  }
  
  return vars;
}
