flowchart TD
    api["api<br/>8 funcs"]
    client["client<br/>1 funcs"]
    client__DslClient["client.DslClient<br/>23 funcs"]
    core["core<br/>9 funcs"]
    frontend__src["frontend.src<br/>20 funcs"]
